var json ={
    "movie1" :{
        "genres" : ["Genres:", "ScienceFiction"],
        "media" : ["Media Type:", "Bluray"],
        "mname" : ["Movie Name:", "Tron Legacy"],
        "date" : ["Movie Date:", "17 December 2010"],
        "note" : ["Notes:", "Not as good as the frist one, story sucked!"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "7"],
    },
    "movie2" :{
        "genres" : ["Genres:", "ScienceFiction"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Tron"],
        "date" : ["Movie Date:", "9 July 1982"],
        "note" : ["Notes:", "Way before its time Love it"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "10"],
    },
    "movie3" :{
        "genres" : ["Genres:", "Adventure"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Mad Max"],
        "date" : ["Movie Date:", "12 April 1979"],
        "note" : ["Notes:", "Why cant they make good moives like this anymore?"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "10"],
    },
    "movie4" :{
        "genres" : ["Genres:", "Comedy"],
        "media" : ["Media Type:", "BluRay"],
        "mname" : ["Movie Name:", "Clerks"],
        "date" : ["Movie Date:", "19 October 1994"],
        "note" : ["Notes:", "funny, good use of black and white "],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "6"],
    },
    "movie5" :{
        "genres" : ["Genres:", "Action"],
        "media" : ["Media Type:", "BluRay"],
        "mname" : ["Movie Name:", "Seven Swords"],
        "date" : ["Movie Date:", "29 July 2005"],
        "note" : ["Notes:", "chinese movie good stuff"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "6"],
    },
    "movie6" :{
        "genres" : ["Genres:", "Comedy"],
        "media" : ["Media Type:", "BluRay"],
        "mname" : ["Movie Name:", "Scott Pilgrim vs. the World"],
        "date" : ["Movie Date:", "13 August 2010"],
        "note" : ["Notes:", "ok but comic books where better"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "6"],
    },
    "movie7" :{
        "genres" : ["Genres:", "Drama"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Azumi"],
        "date" : ["Movie Date:", "10 May 2003"],
        "note" : ["Notes:", "Japanese"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "8"],
    },
    "movie8" :{
        "genres" : ["Genres:", "ScienceFiction"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Kyuti Hani"],
        "date" : ["Movie Date:", "24 May 2004"],
        "note" : ["Notes:", "Japanese"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "8"],
    },
    "movie9" :{
        "genres" : ["Genres:", "Drama"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Azumi 2: Death or Love"],
        "date" : ["Movie Date:", "12 March 2005"],
        "note" : ["Notes:", "Japanese"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "7"],
    },
    "movie10" :{
        "genres" : ["Genres:", "Action"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Ichi"],
        "date" : ["Movie Date:", "25 october 2008"],
        "note" : ["Notes:", "Japanese"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "6"],
    },
    "movie11" :{
        "genres" : ["Genres:", "Action"],
        "media" : ["Media Type:", "Digital"],
        "mname" : ["Movie Name:", "From Paris with Love"],
        "date" : ["Movie Date:", "5 February 2010"],
        "note" : ["Notes:", "itunes"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "9"],
    },
    "movie12" :{
        "genres" : ["Genres:", "Crime"],
        "media" : ["Media Type:", "Digital"],
        "mname" : ["Movie Name:", "Sherlock Homes"],
        "date" : ["Movie Date:", "25 December 2009"],
        "note" : ["Notes:", "itunes, good movie"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "7"],
    },
    "movie13" :{
        "genres" : ["Genres:", "Action"],
        "media" : ["Media Type:", "Digital"],
        "mname" : ["Movie Name:", "Salt"],
        "date" : ["Movie Date:", "23 July 2010"],
        "note" : ["Notes:", "itunes, ok movie"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "4"],
    },
    "movie14" :{
        "genres" : ["Genres:", "Drama"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Apocalypse Now"],
        "date" : ["Movie Date:", "15 August 1979"],
        "note" : ["Notes:", "The Horror... The Horror"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "10"],
    },
    "movie15" :{
        "genres" : ["Genres:", "Drama"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "Full Metal Jacket"],
        "date" : ["Movie Date:", "26 June 1986"],
        "note" : ["Notes:", "Great Movie"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "10"],
    },
    "movie16" :{
        "genres" : ["Genres:", "ScienceFiction"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "2001: A Space Odyssey"],
        "date" : ["Movie Date:", "6 April 1968"],
        "note" : ["Notes:", "book was better"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "7"],
    },
    "movie17" :{
        "genres" : ["Genres:", "Crime"],
        "media" : ["Media Type:", "DVD"],
        "mname" : ["Movie Name:", "A Clockwork Orange"],
        "date" : ["Movie Date:", "2 February 1972"],
        "note" : ["Notes:", "Crazy good fun"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "10"],
    },
    "movie18" :{
        "genres" : ["Genres:", "Drama"],
        "media" : ["Media Type:", "BluRay"],
        "mname" : ["Movie Name:", "Fight Club"],
        "date" : ["Movie Date:", "15 October 1999"],
        "note" : ["Notes:", "the end makes the movie"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "9"],
    },
    "movie19" :{
        "genres" : ["Genres:", "Crime"],
        "media" : ["Media Type:", "BluRay"],
        "mname" : ["Movie Name:", "Lucky Number Slevin"],
        "date" : ["Movie Date:", "7 April 2006"],
        "note" : ["Notes:", "poor guy always getting beat up"],
        "favorite" : ["Favorite:", "Yes"],
        "rating" : ["Rating:", "8"],
    },
    "movie20" :{
        "genres" : ["Genres:", "Crime"],
        "media" : ["Media Type:", "Digital"],
        "mname" : ["Movie Name:", "Reservoir Dogs"],
        "date" : ["Movie Date:", "23 October 1992"],
        "note" : ["Notes:", "good movie, Amazon Video"],
        "favorite" : ["Favorite:", "no"],
        "rating" : ["Rating:", "6"],
    }    
    
}
